import { useState } from 'react';

const TOPICS = ['Food', 'History', 'Nightlife', 'Best Time to Visit'];

export default function DiscoverMore({ cityName, citySlug }) {
  const [activeTopic, setActiveTopic] = useState(null);
  const [answer, setAnswer] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  async function handlePillClick(topic) {
    setActiveTopic(topic);
    setAnswer(null);
    setError(false);

    const cacheKey = `ai:${citySlug}:${topic}`;
    const cached = localStorage.getItem(cacheKey);
    if (cached) {
      setAnswer(cached);
      return;
    }

    setLoading(true);
    try {
      const res = await fetch('/api/ask-ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ city: cityName, topic }),
      });
      const data = await res.json();
      if (data.answer) {
        setAnswer(data.answer);
        localStorage.setItem(cacheKey, data.answer);
      } else {
        setError(true);
      }
    } catch (err) {
      setError(true);
    } finally {
      setLoading(false);
    }
  }

  function closePanel() {
    setActiveTopic(null);
    setAnswer(null);
    setError(false);
  }

  return (
    <div style={{ marginTop: '20px', marginBottom: '20px' }}>
      <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '10px' }}>Discover more</p>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
        {TOPICS.map((topic) => (
          <button
            key={topic}
            onClick={() => handlePillClick(topic)}
            style={{
              backgroundColor: 'var(--bg-card)',
              border: '1px solid var(--border)',
              borderRadius: '999px',
              padding: '8px 16px',
              color: 'var(--text)',
              fontSize: '13px',
              cursor: 'pointer',
            }}
          >
            {topic} in {cityName}
          </button>
        ))}
      </div>

      {activeTopic && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            right: 0,
            height: '100vh',
            width: '360px',
            maxWidth: '90vw',
            backgroundColor: 'var(--bg-card)',
            borderLeft: '1px solid var(--border)',
            boxShadow: '-4px 0 20px rgba(0,0,0,0.3)',
            padding: '24px',
            overflowY: 'auto',
            zIndex: 100,
          }}
        >
          <button
            onClick={closePanel}
            style={{
              background: 'none',
              border: '1px solid var(--border)',
              borderRadius: '8px',
              padding: '6px 12px',
              color: 'var(--text-muted)',
              cursor: 'pointer',
              fontSize: '13px',
              marginBottom: '20px',
            }}
          >
            ✕ Close
          </button>
          <h3 className="font-display" style={{ fontSize: '20px', marginBottom: '8px', color: 'var(--text)' }}>
            {activeTopic} in {cityName}
          </h3>
          <p style={{ fontSize: '12px', color: 'var(--gold)', marginBottom: '16px' }}>✨ Generated by Gemini</p>

          {loading && <p style={{ color: 'var(--text-muted)', fontSize: '14px' }}>Loading...</p>}
          {error && <p style={{ color: '#B5544A', fontSize: '14px' }}>Something went wrong. Please try again.</p>}
          {answer && (
            <p style={{ color: 'var(--text)', fontSize: '14px', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>
              {answer}
            </p>
          )}
        </div>
      )}
    </div>
  );
}